mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.qihang.sys.api.domain;com.qihang.security.entity;
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 开启sql日志
#mybatis:
#  mapper-locations: classpath*:mappers/user/*.xml

spring:
  application:
    name: offline-api

server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/


